; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:freenove_esp32_s3_wroom]
platform = espressif32
board = freenove_esp32_s3_wroom
framework = arduino
monitor_speed = 9600
lib_deps = 
	adafruit/Adafruit GFX Library@^1.12.1
	adafruit/Adafruit SSD1306@^2.5.15
	adafruit/Adafruit BMP085 Library@^1.2.4
	adafruit/DHT sensor library@^1.4.6
	knolleary/PubSubClient@^2.8
	bblanchon/ArduinoJson@^7.4.2
	mikalhart/TinyGPSPlus@^1.1.0
	adafruit/Adafruit NeoPixel@^1.15.1
	adafruit/Adafruit BusIO@^1.17.2
	adafruit/Adafruit MPU6050@^2.2.6
	rfetick/MPU6050_light@^1.1.0
